{% set name = 'psocake' %}
{% set version = '00.06.04' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lcls-psana/{{ name }}/archive/V00-06-04.tar.gz
  sha256: 1544f2c3a1653aec8d2fc25458eef9006f925b087fb06a319d295620c0b09f5d

build:
  skip: True  # [win or osx]
  number: 8
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python=2.7.15
    - setuptools=44.0.0
    - pip=20.1.1
  run:
    - python=2.7.15
    - numpy=1.16.5
    - scipy=1.2.0
    - pandas=0.24.2
    - pyqtgraph=0.11.0
    - pyqt=5.12.3
    - h5py=2.10.0
    - scikit-learn=0.20.4
    - mpi4py=3.0.3
    - scikit-image=0.14.3

test:
  imports:
    - psocake

about:
  home: https://lcls.slac.stanford.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data analysis software for Free-Electron Lasers'
  description: |
    making data analysis for free-electron lasers a piece of cake.
  doc_url: https://github.com/lcls-psana/psocake/blob/master/README.md  
  dev_url: https://github.com/slaclab/psocake

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
